### ISSUE TITLE
Please make Svelte 4 documentation available

### ISSUE THREAD

**Issue by dotterian** [sveltejs/svelte.dev#642] opened 2024-10-25 15:51 UTC
Hi there.
I wish I could read Svelte 4 docs somewhere, since I have no intention on rewriting entirety of my codebase to Svelte 5 dealing with quirks that may occur while migrating.
Please, don't abandon old docs, it worth nothing to add ability to switch version of docs on website.

**Comment by brunnerh** [comment] 2024-10-25 15:52
Duplicate of:
- #524

**Closed by brunnerh** 2024-10-25 15:52 UTC
