### ISSUE TITLE
Dynamic imports break the playground

### ISSUE THREAD

**Issue by Serator** [sveltejs/svelte.dev#659] opened 2024-10-26 18:44 UTC
[Repro with runes](https://svelte.dev/playground/untitled?version=5.1.3#H4sIAAAAAAAAE3WRQW-DMAyF_4rlTSpICO4MkKZde91p7JCCkaIFJyJmW4f471Oadmslekr03mfnOV6Q1UhY4iuLFkM9ZjhoQx7LtwXl6IIXBMwu5LNzuf8kI0E7KE9bemdZiMVjiZXvJu2kabkVQwJ79aPNcW9VT_2LHZ1lYoEaHr0ooSR9arkq_mt4edDDdtHaMkC13a9oWl5KMp4idZhFLIcrgOXO6O6jXpQ_cgdJCnUDS_Tgbr5EfSktoEdnJ0l2eXENniffpWne06BmI7HdusYz_GTd4jkFBrGJTqiHv3dOWYuIhQkKPayYodC3YCnTTGt2Zy0baW73sw1cL8o1kQFzgqC7pKoK19ymeF9_AbDWk1Q6AgAA)

Based on [this](https://github.com/sveltejs/svelte/issues/12663) issue.

<img width="1335" alt="image" src="https://github.com/user-attachments/assets/db0bcb12-112c-4f82-a488-ff2de39e883e">

**Comment by brunnerh** [comment] 2024-10-26 20:28
Duplicate of:
- #503

**Closed by brunnerh** 2024-10-26 20:28 UTC
