### ISSUE TITLE
Playground: Dynamically loading component doesn't compile - RollupError: Invalid value "iife" for option "output.format"

### ISSUE THREAD

**Issue by Leonidaz** [sveltejs/svelte.dev#727] opened 2024-10-30 20:43 UTC
[Playground link to repro](https://svelte.dev/playground/2b421e25fe45429eb1d68a4b60a13c15?version=5.1.6)

Steps to reproduce:
- click on the playground link
- check the browser console

Error:
```
index-DvtQ4obt.js:113 RollupError: Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
    at Xi (index-DvtQ4obt.js:25:919)
    at F (index-DvtQ4obt.js:25:870)
    at index-DvtQ4obt.js:56:1241
    at qp.generate (index-DvtQ4obt.js:56:1864)
    at async index-DvtQ4obt.js:57:45862
    at async ng (index-DvtQ4obt.js:113:163)
    at async index-DvtQ4obt.js:81:185
```

**Comment by Conduitry** [comment] 2024-10-30 20:49
Duplicate of #503.

**Closed by Conduitry** 2024-10-30 20:49 UTC
