### ISSUE TITLE
REPL: Broken history of changes

### ISSUE THREAD

**Issue by 7nik** [sveltejs/svelte.dev#591] opened 2024-10-23 19:05 UTC
### Describe the bug

Undoing (Ctrl+Z) cycles between the current code and the previous one instead of going down through all the history of changes.

### Reproduction

https://svelte.dev/playground/hello-world

Do a few changes.
Try to undo them all.

### System Info

```shell
REPL.
```

### Severity

annoyance

**Comment by brunnerh** [comment] 2024-10-23 19:54
Duplicate of:
- #484

**Closed** 2024-10-23 21:18 UTC
Labels: bug
