### ISSUE TITLE
[Tutorial]POST handlers don't trigger ul reload

### ISSUE THREAD

**Issue by ros-viper** [sveltejs/svelte.dev#865] opened 2024-11-13 23:10 UTC
In Basic SvelteKitAPI / routes/ POST handlers tutorial once we add a new todo item, the list isn't automatically reloaded in this bit:
```
<input
	type="text"
	autocomplete="off"
	onkeydown={async (e) => {
		if (e.key !== 'Enter') return;

		const input = e.currentTarget;
		const description = input.value;
		
		const response = await fetch('/todo', {
	            method: 'POST',
	            body: JSON.stringify({ description }),
	            headers: {
		            'Content-Type': 'application/json'
	            }
		});

		const { id } = await response.json();

		data.todos = [...data.todos, {
	            id,
	            description
		}];

		input.value = '';
	}}
/>
```
The bit data.todos = ... doesn't trigger reload. In order for the list of todos to react to entering a new todo, we need to reinitialise data pro itself by adding ```data = {...data}``` after updating todos array. So, it should look like this possibly:
```
<input
	type="text"
	autocomplete="off"
	onkeydown={async (e) => {
		if (e.key !== 'Enter') return;

		const input = e.currentTarget;
		const description = input.value;
		
		const response = await fetch('/todo', {
	            method: 'POST',
	            body: JSON.stringify({ description }),
	            headers: {
		            'Content-Type': 'application/json'
	            }
		});

		const { id } = await response.json();

		data.todos = [...data.todos, {
	            id,
	            description
		}];

                //this makes the todo list reload
                data = {...data};

		input.value = '';
	}}
/>
```

**Comment by Conduitry** [comment] 2024-11-13 23:18
Duplicate of #786.

**Closed** 2024-11-13 23:18 UTC
