### ISSUE TITLE
docs: Template syntax (use:) types not rendering properly

### ISSUE THREAD

**Issue by TheGroobi** [sveltejs/svelte.dev#885] opened 2024-11-25 12:35 UTC
### Describe the bug

On the official docs, https://svelte.dev/docs/svelte/use#Typing under Typing  When switching to typescript the brackets are being removed

This is the code from the JS version with JSDoc:

![image](https://github.com/user-attachments/assets/72ee421e-9ab9-4871-95d3-77963d92db0f)

Switching to typescript:
![image](https://github.com/user-attachments/assets/b6b7e939-b618-4915-bc3b-326c1ecd384b)

The Action type is missing brackets at the end of the third generic:

```ts
const gestures: Action<HTMLDivElement, null, {
			onswiperight: (e: CustomEvent) => void;
			onswipeleft: (e: CustomEvent) => void; 
// these two brackets ↓
                 }> 
= (node) => {
...
}
```

### Reproduction

not needed

### System Info

```shell
not needed
```

### Severity

annoyance

**Comment by Conduitry** [comment] 2024-12-11 20:18
Duplicate of #647.

**Closed by Conduitry** 2024-12-11 20:18 UTC
