### ISSUE TITLE
Code example on `use:` documentation is invalid

### ISSUE THREAD

**Issue by thonkinator** [sveltejs/svelte.dev#983] opened 2024-12-11 13:45 UTC
The TypeScript code example at the bottom of https://svelte.dev/docs/svelte/use is invalid syntax. there's supposed to be a `}>` after the second `=> void`, like this:
```ts
const gestures: Action<
    HTMLDivElement,
    null,
    {
        onswiperight: (e: CustomEvent) => void;
        onswipeleft: (e: CustomEvent) => void;
    }
> = (node) => {
    $effect(() => {
        // ...
        node.dispatchEvent(new CustomEvent("swipeleft"));

        // ...
        node.dispatchEvent(new CustomEvent("swiperight"));
    });
};
```

**Comment by Conduitry** [comment] 2024-12-11 20:17
Duplicate of #647.

**Closed by Conduitry** 2024-12-11 20:17 UTC
