### ISSUE TITLE
Playground: result tab always show compiled code from App.svelte

### ISSUE THREAD

**Issue by paoloricciuti** [sveltejs/svelte.dev#766] opened 2024-11-02 14:48 UTC
As per title, even if you switch file the output is always the one from App svelte

**Comment by Conduitry** [comment] 2024-11-02 15:05
I can't reproduce this. On https://svelte.dev/playground/nested-components, for example, what's shown in "JS output" Is whatever file I have selected on the left side.

**Comment by brunnerh** [comment] 2024-11-02 15:11
Also had this issue before but don't have a reproduction at hand.
Maybe it can break due to certain errors.

**Comment by paoloricciuti** [comment] 2024-11-02 15:13
It might be just for `.svelte.js` files then...try to create a .svelte.js file in that example and at least for me is not showing it

**Comment by Conduitry** [comment] 2024-11-02 15:28
Ah, yep, I do see it for `.svelte.js` files.

**Comment by Rich-Harris** [comment] 2024-11-02 17:27
I can't reproduce this. What are the exact steps? (It's _possible_ though unlikely that it was accidentally fixed in #767)

**Comment by Conduitry** [comment] 2024-11-02 17:37
1 - open https://svelte.dev/playground/hello-world?version=5.1.9#H4sIAAAAAAAACnWOyw6CMBBFf6XOBk0IxC1WEnb-g3WBMAZMnTZ0fIXw77ZKokTdnrlz7-mByhNCBhvU2oir6XQt5li3jPUCYji0Gh1k2x74bkMuAM_Hr8LaxF1Qc2D70uEvXhliJPY1IF3VtZZzRYo1sghxsRbRczdaKZLpO0GyWeYvrz4Eh5lMPVHkOxlvDBl3ZxziP26MjkeJ5Oimfl-3D8cmLE4ndsMDdWWbZygBAAA=
2 - switch to "test.svelte.js"
3 - switch to "JS output"

or swap 2 and 3

**Closed** 2024-11-02 18:02 UTC
Labels: playground (functionality)
