### ISSUE TITLE
Missing tutorial link in v5 migration page 

### ISSUE THREAD

**Issue by shivan-s** [sveltejs/svelte.dev#561] opened 2024-10-23 03:30 UTC
![CleanShot 2024-10-23 at 16 22 31](https://github.com/user-attachments/assets/973076b0-65d5-44bc-8974-051f72470d88)

Located in the [v5 migration guide](https://svelte.dev/docs/svelte/v5-migration-guide#Reactivity-syntax-changes-let-$state) (as shown in the screenshot), I'm guessing we expect to have a link to the tutorial link, I'm going to guess it's this: https://svelte.dev/tutorial/svelte/state

I can create a PR for this. Hope it helps.

**Comment by Conduitry** [comment] 2024-10-23 03:37
Duplicate of https://github.com/sveltejs/svelte/issues/13787 / https://github.com/sveltejs/svelte/pull/13796. Changes like this are made in the Svelte repo - it just hasn't been synced yet to this repo.

**Closed by Conduitry** 2024-10-23 03:37 UTC
