### ISSUE TITLE
Broken permalinks

### ISSUE THREAD

**Issue by mrexodia** [sveltejs/svelte.dev#636] opened 2024-10-25 12:26 UTC
I searched for `svelte onmount` and got the following URL: https://learn.svelte.dev/tutorial/onmount

![image](https://github.com/user-attachments/assets/6d42a360-0237-49dd-8094-96dece28fbf5)

This leads to a 404.

**Comment by benmccann** [comment] 2024-10-25 12:36
Duplicate of https://github.com/sveltejs/svelte.dev/issues/619

**Closed by benmccann** 2024-10-25 12:36 UTC
